### ISSUE TITLE
NoMethodError: undefined method `only_deleted' for parent model. Does the  'restore' with 'recursive: true' option really take effect in rails4?

### ISSUE THREAD

**Issue by Feuda** [rubysherpas/paranoia#147]
pry(main)> Project.find(199).destroy

<code>
  (0.1ms)  BEGIN
  SQL (0.4ms)  UPDATE `publications` SET `publications`.`updated_at` = '2014-07-22 07:15:33', `publications`.`deleted_at` = '2014-07-22 07:15:33' WHERE `publications`.`id` = 549
   (21.4ms)  COMMIT
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE `projects` SET `projects`.`updated_at` = '2014-07-22 07:15:33', `projects`.`deleted_at` = '2014-07-22 07:15:33' WHERE `projects`.`id` = 199
   (23.1ms)  COMMIT
</code>
pry(main)> Project.restore(199, :recursive => true)
<code>
Project Load (0.6ms)  SELECT `projects`.\* FROM `projects` WHERE (`projects`.`deleted_at` IS NOT NULL) AND `projects`.`id` = 199 LIMIT 1
   (0.2ms)  BEGIN
  SQL (0.3ms)  UPDATE `projects` SET `projects`.`deleted_at` = NULL WHERE `projects`.`id` = 199
  Publication Load (2.0ms)  SELECT `publications`.\* FROM `publications` WHERE `publications`.`deleted_at` IS NULL AND `publications`.`as_publication_id` = 199 AND `publications`.`as_publication_type` = 'Project' ORDER BY `publications`.`id` ASC LIMIT 1
   (32.0ms)  ROLLBACK
NoMethodError: undefined method `only_deleted' for #Publication:0xdf8ee60
</code>

**Comment by Feuda** [comment]
Why the publications.deleted_at IS NULL but not IS NOT NULL in the Publication Load?

**Comment by radar** [comment]
Hi @Feuda, please provide steps for me to reproduce this issue in a new project.

**Comment by Feuda** [comment]
I used this gem http://hzamani.github.com/acts_as_relation/ to realize Multi table Inheritance, in my case, publication is the parent, project is one of children. @radar

**Comment by brandonparsons** [comment]
I am also seeing rollbacks when trying to do a recursive restore in rails 4.1.  The issue seems to be with `NULL` in the related model vs. `NOT NULL` in the parent.

```
[31] (pry) main: 0> User.restore(u.id, recursive: true)
  User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE ("users"."deleted_at" IS NOT NULL) AND "users"."id" = $1 LIMIT 1  [["id", "08b71755-f573-455e-805b-e4801d4a999d"]]
   (0.1ms)  BEGIN
  SQL (0.4ms)  UPDATE "users" SET "deleted_at" = NULL WHERE "users"."id" = '08b71755-f573-455e-805b-e4801d4a999d'
  Questionnaire Load (0.2ms)  SELECT  "questionnaires".* FROM "questionnaires"  WHERE "questionnaires"."deleted_at" IS NULL AND "questionnaires"."user_id" = $1 LIMIT 1  [["user_id", "08b71755-f573-455e-805b-e4801d4a999d"]]
   (0.1ms)  ROLLBACK
NoMethodError: undefined method `paranoid?' for nil:NilClass
from /Users/brandon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paranoia-2.0.2/lib/paranoia.rb:107:in `block in restore_associated_records'
```

Note `NOT NULL` constraint for the user, and `NULL` constraint for the questionnaire. As the questionnaire is also soft-deleted, the constraint should be `... deleted_at" IS NOT NULL`

**Comment by adamwaite** [comment]
@brandonparsons I'm seeing the same issue. Is there a fix?

**Comment by adamwaite** [comment]
Ah, i'm pretty sure it's related to:  https://github.com/radar/paranoia/pull/123

@JeskTop fixed it for Rails 3 but it hasn't been merged into Rails 4 yet due to a failing CI build?

**Comment by JeskTop** [comment]
@adamwaite Yes, failing CI build in rails 4.0.8. I could not find the problem in the test.

```
test/paranoia_test.rb:42:in `setup'
```

I check it and use rails 4.0.8 in my computer, but is success pass the test and nothing wrong. So I very confused.

**Comment by bluej100** [comment]
https://github.com/radar/paranoia/pull/123 was merged into Rails 4 on Sep 16th. @adamwaite , is this still an issue?

**Comment by adamwaite** [comment]
I decided to remove it in the end. Will report back when I get a bit of time.

**Comment by bluej100** [comment]
restore(recursive: true) is working in my Rails 4 app for both has_many and has_one.

**Comment by jhawthorn** [comment]
I'm closing this. @adamwaite could you please reopen this if the issue persists.

We've had a couple fixes to has_one associations, #123 (as @bluej100 kindly points out) as well as #171. So please give another try with version 2.0.4.
