### ISSUE TITLE
Overriding getter to access soft-deleted associations not working

### ISSUE THREAD

**Issue by reedlaw** [rubysherpas/paranoia#109]
From the README:

If you want to access soft-deleted associations, override the getter method:

``` ruby
def product
  Product.unscoped { super }
end
```

But it only works if you're willing to tolerate N+1 queries. That is, if you add `.includes` to your scope, then the getter override method is not called. [Here is a commit](https://github.com/reedlaw/paranoia_gem_unscoped_demo/commit/bc079f91d804836d6a423bd99df07e57fe4723b6) that reproduces the problem in a sample app. In the controller, the scope is build with `.includes`. If you have a couple or more users each with associated company and posts, then you will see queries like these:

```
Started GET "/users" for 127.0.0.1 at 2014-02-11 16:30:21 -0500
Processing by UsersController#index as HTML
  User Load (0.3ms)  SELECT "users".* FROM "users"
  Company Load (0.1ms)  SELECT "companies".* FROM "companies" WHERE "companies"."deleted_at" IS NULL AND "companies"."id" IN (1, 2)
  Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."deleted_at" IS NULL AND "posts"."user_id" IN (1, 2)
```

**Comment by radar** [comment]
@reedlaw What do you propose then to fix this? I don't know how we could override how AR is loading those scopes.

**Comment by reedlaw** [comment]
So is this a bug in AR? It seems like scopes should be honored regardless of how the query is built.

**Comment by radar** [comment]
@reedlaw I think AR is behaving intentionally here. You are not telling it to includes the association where the deleted_at could potentially be `nil`. I think you could define the association like this:

```
belongs_to :company, -> { with_deleted }
```

And it might just work.

**Comment by reedlaw** [comment]
I tried that as well as a named scope with `.includes(:company).with_deleted` but neither work. [See this commit](https://github.com/reedlaw/paranoia_gem_unscoped_demo/commit/029fc8bd4437b469024d678e0e81644d2bdbe9a6). I am able to pass other scopes to associations. I stepped through the execution with a debugger and found it reaching [here](https://github.com/radar/paranoia/blob/rails4/lib/paranoia.rb#L14) at which point the company scope was correct. But at a later point the scope had reverted to include `WHERE "companies"."deleted_at" IS NULL`.

**Comment by radar** [comment]
@reedlaw Have you been able to find a solution for this yet?

**Comment by reedlaw** [comment]
Currently I'm just allowing N+1 queries. If it becomes a performance issue at some point I will have to build the query using raw SQL.

**Comment by steverob** [comment]
Im stuck in this exact same place as well. And I am not able to tolerate the N+1 queries. @radar Any solutions yet? @reedlaw Have you got anything?

Thanks!

**Comment by radar** [comment]
@steverob No solutions yet, sorry. AR and databases in general are a pain.

**Comment by steverob** [comment]
Ohh :( thanks Ryan. I've temporarily removed the default_scope and added my own. Working on a custom SQL query. Till then this is it I guess :) 

Great gem! :) thanks!!

## 

Regards
Steve Robinson

**Comment by radar** [comment]
I _think_ with Rails 4.1 this now might be possible to do with a scope using `unscope`. I'm going to investigate.

**Comment by radar** [comment]
_sigh_

```
irb(main):002:0> comment = Comment.first
  Comment Load (0.1ms)  SELECT  "comments".* FROM "comments"   ORDER BY "comments"."id" ASC LIMIT 1
=> #<Comment id: 1, post_id: 1, created_at: "2014-04-09 00:04:32", updated_at: "2014-04-09 00:04:32">
irb(main):003:0> comment.post
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts"  WHERE "posts"."id" = ? LIMIT 1  [["id", 1]]
=> #<Post id: 1, deleted_at: "2014-04-09 00:04:32", created_at: "2014-04-09 00:04:32", updated_at: "2014-04-09 00:04:32">
irb(main):004:0> Comment.includes(:post).first
  Comment Load (0.2ms)  SELECT  "comments".* FROM "comments"   ORDER BY "comments"."id" ASC LIMIT 1
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"  WHERE "posts"."deleted_at" IS NULL AND "posts"."id" IN (1)
=> #<Comment id: 1, post_id: 1, created_at: "2014-04-09 00:04:32", updated_at: "2014-04-09 00:04:32">
irb(main):005:0>
```

**Comment by steverob** [comment]
Awww :( this is indeed a pain. Thank you so much Ryan!

## 

Regards
Steve Robinson

**Comment by aaronchi** [comment]
Solution extracted from acts_as_paranoid:

```
module Paranoia

  # Adds with_deleted to belongs_to
  module Associations
    def self.included(base)
      base.extend ClassMethods
      class << base
        alias_method_chain :belongs_to, :deleted
      end
    end

    module ClassMethods
      def belongs_to_with_deleted(target, options = {})
        with_deleted = options.delete(:with_deleted)
        result = belongs_to_without_deleted(target, options)

        if with_deleted
          result.options[:with_deleted] = with_deleted
          unless method_defined? "#{target}_with_unscoped"
            class_eval <<-RUBY, __FILE__, __LINE__
              def #{target}_with_unscoped(*args)
                association = association(:#{target})
                return nil if association.options[:polymorphic] && association.klass.nil?
                return #{target}_without_unscoped(*args) unless association.klass.paranoid?
                association.klass.with_deleted.scoping { #{target}_without_unscoped(*args) }
              end
              alias_method_chain :#{target}, :unscoped
            RUBY
          end
        end

        result
      end
    end
  end

  # Loads associations correct with includes
  module PreloaderAssociation
    def self.included(base)
      base.class_eval do
        def build_scope_with_deleted
          scope = build_scope_without_deleted
          scope = scope.with_deleted if options[:with_deleted] && klass.respond_to?(:with_deleted)
          scope
        end

        alias_method_chain :build_scope, :deleted
      end
    end
  end

end

ActiveRecord::Base.send :include, Paranoia::Associations
ActiveRecord::Associations::Preloader::Association.send :include, Paranoia::PreloaderAssociation
```

This involves setting a `:with_deleted => true` on the belongs_to association.

**Comment by timscott** [comment]
@aaronchi This patch was working with Rails 4.0.x, but no more on 4.1.

```
`belongs_to_with_deleted': undefined method `options' for #<Hash:0x007f83ccf0e360> (NoMethodError)
```

Looking into it.

**Comment by timscott** [comment]
@aaronchi The fix seems to be change line 18 to:

``` ruby
result[target].options[:with_deleted] = with_deleted
```

The error goes away, but I have not verified the behavior.

UPDATE:

With Rails 4.1, it needs to be:

``` ruby
result.with_indifferent_access[target].options[:with_deleted] = with_deleted
```

or 

``` ruby
result[target.to_s].options[:with_deleted] = with_deleted
```

I use the former because it's more resilient.

**Comment by aaronchi** [comment]
Does this work in 4.1?

`belongs_to  :post, -> { unscoped }`

**Comment by radar** [comment]
@aaronchi Does it? :)

**Comment by darkside** [comment]
@aaronchi do you know if your monkey patch works for latest Rails 3? The unsolvable N+1 queries are driving me crazy :(

**Comment by aaronchi** [comment]
@darkside. Yes, it should work with Rails 3

**Comment by brchristian** [comment]
Chiming in to say that this is presenting problems for me as well.

I might go so far as to say that a scenario in which `Foo.first.bar != Foo.first.includes(:bar).bar` qualifies as a potential bug/issue in ActiveRecord. Maybe there's a way to get some of the AR authors to comment on a way for soft-delete functionality to work smoothly, even if it involves working together to tweak AR's behavior for that purpose in Rails 4.2 or something.

This seems like a use-case that a lot of people are already confronting, and probably only more people will over time.

**Comment by hx** [comment]
This issues doesn't seem to be resolved yet. What say we reopen it and take another squiz?

**Comment by radar** [comment]
@hx Please do open up a new issue with steps to reproduce.

**Comment by cwjenkins** [comment]
@radar @reedlaw I provided a fix to AR here https://github.com/rails/rails/pull/16531. If its merged the above work around will no longer be required. 

You would be able to unscope the default like so...

```
has_many :with_deleted_gadgets, -> { unscope(where: :deleted_at) }, class_name: "Gadget", foreign_key: :gadget_id

# Preload gadgets unscoped
Something.includes(:with_deleted_gadgets)
```

**Comment by radar** [comment]
Thanks for the heads up @cwjenkins. Please ping here again when that issue is merged.

**Comment by radar** [comment]
Looks like this will be merged with ActiveRecord 5.0.

**Comment by steverob** [comment]
Awesome!! :) :)

## 

Regards
Steve Robinson

**Comment by jdurand** [comment]
I confirm that this issue is fixed as of activerecord 4.2.
Using `includes(:company)` with `belongs_to :company, -> { with_deleted }` associates the soft deleted company.

**Comment by steverob** [comment]
Yaaaaaaayyyy!! :) 

## 

Regards
Steve Robinson

**Comment by radar** [comment]
Wonderful.

@jdurand Can you please submit a new PR to mention this in the README?

**Comment by phlegx** [comment]
How can I override it so, that it works with nested views and accepts_nested_attributes_for :avatar?

**Comment by radar** [comment]
Huh? Can you please explain how it's not working in that one particular context?

**Comment by phlegx** [comment]
I have model user that has one avatar. In my edit user view I use nested attributes for the avatar fields. Starting the form with @user as model the nested attributes of avatar are called through the default scope of avatar. How can I get also deleted avatars from nested attributes. Here a code snipped:

``` ruby
# Adding this in the user controller don't helps to do the following fields_for
def avatar
  Avatar.unscoped { super }
end
```

``` ruby
<!-- This example shows that avatar is called from the default scope -->
<%= form_for @user ... do |f| %>
  <%= f.fields_for :avatar do |avatar| %>
    ... 
```

This could help:

``` ruby
# In the user controller
def avatar
  Avatar.unscoped { super }
end
```

``` ruby
<%= form_for @user ... do |f| %>
  <%= f.fields_for :avatar, @user.avatar do |avatar| %>
    ... 
```

**Comment by radar** [comment]
Why are you defining that in the controller? That unscoping should go in the model, and it should be like:

```
belongs_to :avatar, -> { with_deleted }
```

**Comment by phlegx** [comment]
OK, i give it a try! Thx.

**Comment by phlegx** [comment]
Following is given:

``` ruby
class User < ActiveRecord::Base
  has_one :avatar, -> { with_deleted }, as: :avatarable
  accepts_nested_attributes_for :avatar, allow_destroy: true
  ...
end
```

It don't works if I do the following:
- Upload an Image to user with `fields_for :avatar`
- Image is shown in view after upload
- From view I soft-delete the image by submitting the attribute name `_destroy: 1`
- Now the image is shown as soft-deleted (`deleted_at` has datetime)
- **Selecting the checkbox with carrierwave checkbox attribute name `remove_image: 1` and submitting the form I get an error!**

`[error 404] Couldn't find Avatar with 'id'=2 [WHERE "avatars"."deleted_at" IS NULL]`

The problem can be on Carrierwave itself by calling method `remove_image!`.

Here the parameter hash:

``` ruby
"user" => { "avatar_attributes" => { "remove_image" => "1", "id" => "2" } }
```
